### ISSUE TITLE
WTERMSIG (and others) are unsafe on macOS, but safe on Linux

### ISSUE THREAD

**Issue by Thomasdezeeuw** [rust-lang/libc#1888]
`WTERMSIG` and related functions have been changed to no longer require `unsafe`, seemingly in commit 5a1df22a783ee0348a4c862e36480a50829a95f5. However on macOS these functions are still `unsafe`. See the definition on Linux https://docs.rs/libc/0.2.77/libc/fn.WTERMSIG.html (no `unsafe`) vs. macOS https://docs.rs/libc/0.2.77/x86_64-apple-darwin/libc/fn.WTERMSIG.html (requires `unsafe`). Was it intentional to leave macOS out?

Also this causes warnings, e.g. see https://github.com/rust-lang/rust/pull/76561/checks?check_run_id=1096958697#step:23:213 (https://github.com/rust-lang/rust/commit/7c3e1ffd7a945b4044e5e80d7d74ba944ff54d0f/checks/1096958697/logs).

/cc @joshtriplett who wrote the commit.

**Comment by joshtriplett** [comment]
It's not that I intentionally left macOS out, I just didn't go changing any other targets systematically in that first commit. Now that the infrastructure is in place, by all means we should update various other functions to use it, including on other targets.

And yes, I'm not surprised that this resulted in "unused unsafe" warnings. We should prioritize adding this to matching functions for other targets, to avoid having problems where one target wants unsafe and another doesn't.

**Comment by joshtriplett** [comment]
https://github.com/rust-lang/libc/commit/773f5562ba04ad8b7ba772e99645922ea908be76 should fix this on all platforms. The fix should be available in the next release of the libc crate.

**Comment by xmo-odoo** [comment]
@joshtriplett @Thomasdezeeuw rustc's `Cargo.lock` pins to 0.2.85 which was released on Feb. 2, 2021. The unsafe blocks & warning suppressions are still present in the latest rustc, are they still necessary?

**Comment by Thomasdezeeuw** [comment]
@xmo-odoo @joshtriplett did that in https://github.com/rust-lang/rust/commit/16ebf750cfbc3de36cbf2e05eb50669d83c4dbfd.

**Comment by xmo-odoo** [comment]
@Thomasdezeeuw 
> did that in [rust-lang/rust@16ebf75](https://github.com/rust-lang/rust/commit/16ebf750cfbc3de36cbf2e05eb50669d83c4dbfd).

Uh. Weird, I wonder what I fucked up that [I apparently reached an outdated revision](https://github.com/rust-lang/rust/blob/154f1f544dd68f7b53ff8d9952811e855f4c2d7c/library/std/src/sys/unix/process/process_unix.rs#L456-L496) (through the github search according to my browser history, but now it links to an up-to-date one).

Sorry about that.
